Revert "Perlito5 - java - avoid an eval-string in jperl.pl"
This reverts commit 6886b0355aae023860a0221e32779272171558c0.

Errors:

t5/op/hexfp.t ............................... 1/79
org.perlito.Perlito5.PlDieException: Error in BEGIN block: missing value
after operator 'x' at t5/op/hexfp.t line 1739

t5/unit/array_strict.t ...................... 1/3
org.perlito.Perlito5.PlDieException: Error in BEGIN block: Can't use an
undefined value as an ARRAY reference at t5/unit/array_strict.t